//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.App_Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Cuentas
    {
        public string user_id { get; set; }

        [Required(ErrorMessage ="Debes escribir tu correo!")]
        public string Correo { get; set; }

        [Required(ErrorMessage = "Debes escribir tu contraseña!")]
        public string Password { get; set; }

        [Required(ErrorMessage = "Debes escribir tu Nombre de usuario!")]
        public string Username { get; set; }

        [Required(ErrorMessage = "Debes escribir tu Compañía!")]
        public string Compania { get; set; }

        public byte[] Foto { get; set; }
    }
}
