//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.App_Data
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.ComponentModel.DataAnnotations;

    public partial class Cuentas
    {
        [Required(ErrorMessage = "Debe ingresar su correo!")]
        public string Correo { get; set; }

        [Required(ErrorMessage = "Debe ingresar su contraseña!")]
        public string Password { get; set; }
        public string Username { get; set; }
        public string Compania { get; set; }
        public byte[] Foto { get; set; }
    }
}
