//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Foro
    {
        public int ID_Foro { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Autor { get; set; }
        public byte[] Logo { get; set; }
        public string ID_Categoria { get; set; }
        public string Correo_Compania { get; set; }
        public string Ubicacion { get; set; }
        public string Url { get; set; }
    }
}
