//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuentas
    {
        public string user_id { get; set; }
        public string Correo { get; set; }
        public string Password { get; set; }
        public string Username { get; set; }
        public string Compania { get; set; }
        public byte[] Foto { get; set; }
    }
}
